:icons: font

== README

Este repositório contém o código fonte do livro https://start-concurrent.github.io[Start Concurrent: A Gentle Introduction to Concurrent Programming], essa é uma tradução livre, autorizada pelos autores https://github.com/bwittman[@bwittman] e https://github.com/jtkorb[@jtkorb], como segue na https://github.com/start-concurrent/start-concurrent.github.io/issues/145[issue #145]. Este livro está licenciado sob  https://github.com/start-concurrent/start-concurrent.github.io/blob/master/LICENSE[Apache License 2.0].

=== Softwares necessários

==== Básico

. https://git-scm.com/downloads[Git] (e uma conta no https://github.com[GitHub] para acessar repositório
https://github.com/start-concurrent/start-concurrent.github.io[Start Concurrent])
. https://www.ruby-lang.org/en/downloads/[Ruby]
. https://asciidoctor.org[Asciidoctor]
. https://github.com/asciidoctor/asciidoctor-mathematical[Asciidoctor-Mathematical] (note special instructions below for installing Mathematical on MacOS Mojave)

==== Pacotes para dividir o livro em um arquivo por Capítulo

. https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker] (para converter para pedaços HTML)
. https://github.com/roswell/roswell[Roswell] (necessário para Asciidoctor Chunker)

==== MacOS: Instalando o Mathematical (e o Asciidoctor-Mathematical) no Mojave (10.14.x)

. Corrija o local do arquivo de cabeçalho do MacOS executando este comando em uma janela de terminal: `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`.
. Adicione o caminho do pacote Homebrew a PKG_CONFIG_PATH (por exemplo, em .bash_profile): `export PKG_CONFIG_PATH=“/usr/local/lib/pkgconfig”`

Essas instruções são altamente dependentes da situação.  Consulte https://stackoverflow.com/questions/51274905/brew-install-on-mojave[Brew Install on Mojave] para obter sugestões adicionais.

=== Editando as ilustrações

A maioria (todas?) das "`figuras`" no livro são feitas com o https://www.adobe.com/products/illustrator.html[Adobe Illustrator] e salvas em formato PDF, e estão localizadas na pasta `figures` de cada capítulo em que aparecem.  Para cada arquivo PDF, há um arquivo SVG correspondente localizado na pasta `images`.  O arquivo SVG é o que é importado pelo arquivo AsciiDoc.

Para criar uma nova figura ou editar uma já existente...

. Crie ou edite o arquivo do Illustrator no subdiretório de figuras.
. Salvar as alterações usando o formato padrão (PDF).
. Converter temporariamente todo o texto em contornos:
.. `Select > Select All`
.. `Type > Create Outlines`
. Em seguida, `Save a Copy As...`, usando o formato SVG e desmarcando a opção “`Preserve Illustrator Editing Capability`”, para criar um arquivo .SVG no subdiretório `images`.

Observação: não salve a versão de texto delineada de volta no arquivo PDF original!

=== Gerando o arquivo HTML

`$ ruby update-html.rb`

Observação: o plug-in https://github.com/jirutka/asciidoctor-rouge[Asciidoctor Rouge] é necessário para realçar a sintaxe.

=== Gerando um arquivo HTML por capítulo

. Instale https://github.com/wshito/asciidoctor-chunker[Asciidoctor Chunker], incluindo
https://github.com/roswell/roswell[Roswell].
. Crie a versão HTML completa do livro: +
`ruby update-html.rb`
. Converter usando o Asciidoctor Chunker (com `ascidoctor-chunker.ros` em seu caminho): +
`$ asciidoctor-chunker.ros full/index.html -o chunked`

Um script UNIX para atualizar as versões completa e em pedaços do HTML está localizado no diretório raiz (`update-html`).

=== Geração do PDF

. Instale a gema https://asciidoctor.org/docs/asciidoctor-pdf/[Asciidoctor PDF].
. Execute o Asciidoctor PDF para fazer a conversão: +
`$ (cd full; asciidoctor-pdf index.adoc -D ../pdf)`

==== Solução alternativa especial para tabelas

Há um bug no código https://github.com/prawnpdf/prawn-table[prawn-table] usado pelo Asciidoctor-PDF ao formatar determinadas tabelas.  Há uma discussão e uma correção (até agora incompleta) https://discuss.asciidoctor.org/Problem-using-Asciidoctor-PDF-to-format-wide-autowidth-table-header-cells-td7220.html[aqui].

Etapas para corrigir o problema (simplificado para não usar um Gemfile):

. Baixe o código mais recente do prawn-table em um repositório separado.
.. `git clone https://github.com/prawnpdf/prawn-table.git`
.. `cd prawn-table`
. Compilar e instalar.
.. `gem build prawn-table.gemspec`
.. `gem install prawn-table-0.2.3.gem`

Essas etapas não corrigem todas as tabelas.  Especificamente, nem todas as tabelas com largura automática funcionarão.  Conselho
do Asciidoctor https://discuss.asciidoctor.org/Problem-using-Asciidoctor-PDF-to-format-wide-autowidth-table-header-cells-tp7220p7229.html[authority] é usar as proporções das colunas e a largura da tabela.

=== Geração de formatos de E-Book

ATENÇÃO: Em progresso.

. Atualizar fontes de livros para que estejam de acordo com o formato exigido. (Uma vez; em andamento.)
. Instalar o https://asciidoctor.org/docs/asciidoctor-epub3/[AsciiDoctor EPUB3 gem].
. Execute o Asciidoctor EPUB3 para fazer a conversão: +
`$ (cd full; asciidoctor-epub3 index.adoc -D ../epub3)`
. Etapas adicionais (TBD) convertem o documento para o formato Kindle (KF8/MOBI).

Outras gemas necessárias (aparentemente):

* https://rubygems.org/gems/gepub[gepub]
* https://rubygems.org/gems/epubcheck[epubcheck]
